### ISSUE TITLE
Can i change sounds for chirp-gpt, and how?

### ISSUE THREAD

**Issue by ubzek08** [merlin-ka/chirp-gpt#1]

**Comment by merlin-ka** [comment]
Yes, but it requires some manual work.

If you have Python installed, the easiest way is to just clone/download the repository and replace the .wav files in the `sounds` directory. Then you just have to run the script `build.py` and replace the code in Tampermonkey (or whatever extension you're using) with the content of `chirp-gpt.user.js`.

If you take a look at the bottom of `chirp-gpt.user.js`, the sound files are just Base64 encoded and pasted into the script. You can also do that manually.

MP3 files or any other format your browser supports should work too, but you will have to change the extension in the build script if you want to use it:

https://github.com/merlin-ka/chirp-gpt/blob/6329194f70b610c352796eb2ee2f9099adf36b7a/build.py#L5

If you replace the sounds, you might want to tweak the values of `PLAY_INTERVAL` and `DETUNE` at the top of the script:

https://github.com/merlin-ka/chirp-gpt/blob/6329194f70b610c352796eb2ee2f9099adf36b7a/script.js#L14-L15
